### ISSUE TITLE
Pretransforming assets failed with Focal Point

### ISSUE THREAD

**Issue by hasco0182** [sjelfull/imagerpretransform#2]
I'm getting a failed task notice if I try to run the Pretransform task in the asset manager in Craft 2.6.2997 with the Focal Point plugin 1.1.7 and Imager Pretransform 1.0.4. My config.php looks as follows:

```PHP
<?php
return [
    'transforms' => [
        [
            'width' => 1200,
        ],
        [
            'width' => 1024,
        ],
        [
            'width' => 768,
            'jpegQuality' => 65
        ],

        'defaults' => [
            'format' => 'jpeg',
            'allowUpscale' => false,
            'mode' => 'crop',
            'jpegQuality' => 80,
            'position' => function ($asset) {
                return $asset->focalPointField;
            },
        ]
    ]
];
```
It works without the position.

**Comment by sjelfull** [comment]
Do you have any errors in your logs?

**Comment by hasco0182** [comment]
My **imager.log** contains the following error several times from around the time I was messing around with the plugin. I can't seem to find any other related errors.
> Request for running tasks immediately failed with http status 302

**Comment by peteeveleigh** [comment]
Was there a resolution to this? I'm seeing the same problem.

**Comment by sjelfull** [comment]
HTTP status 302 sounds like there is some kind of redirect in there. Do you have any rewrites setup that might be kicking in?

Besides that hunch, I don't have anything specific to go on here. I would need more specific error messages.

So far this does not look related to the plugin itself.

**Comment by sjelfull** [comment]
Closing due to no follow-ups. Let me know if this is related to the plugin.
